formatter: markdown

content: |-
    {{ .Header }}

    ## Usage

    Example:
    
    ```hcl
    {{ include "examples/main.tf" }}
    ```

    ## Scripts

    The [push.bash](scripts/push.bash) script uses `docker` by default to build and push the container image.

    It is possible to use a different command, by setting the `DOCKER_CMD` environment variable before running the `terraform` commands.

    Examples:

    ```sh
    export DOCKER_CMD='podman'
    terraform apply
    ```

    ```sh
    export DOCKER_CMD=`lima nerdctl`
    terraform apply
    ```

    {{ .Footer }}

    {{ .Inputs }}

    {{ .Modules }}

    {{ .Outputs }}

    {{ .Providers }}

    {{ .Requirements }}

    {{ .Resources }}


output:
  file: README.md
  mode: inject
  template: |-
    [//]: # (BEGIN_TF_DOCS)
    {{ .Content }}

    [//]: # (END_TF_DOCS)

